# Generated by Django 6.0.6 on 2026-06-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.player')),
            ],
            options={
                'ordering': ['-value', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'Game Statistic',
                'verbose_name_plural': 'Game Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.score',),
        ),
    ]
